// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAnDl3E9pFYiBJ0-G06I8uZLrl5jZyY78I',
    appId: '1:329239862452:web:81f6268af2f84a57a04be1',
    messagingSenderId: '329239862452',
    projectId: 'authentication-75ad0',
    authDomain: 'authentication-75ad0.firebaseapp.com',
    storageBucket: 'authentication-75ad0.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC280suodFBM1wDNYP-FSqxy7LyYG5hjwQ',
    appId: '1:329239862452:android:97ea62fab057d1a3a04be1',
    messagingSenderId: '329239862452',
    projectId: 'authentication-75ad0',
    storageBucket: 'authentication-75ad0.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDnvHfhTtSrWABAYn2k8M0EhY6xIaVGQLE',
    appId: '1:329239862452:ios:3207a057ce876a6ea04be1',
    messagingSenderId: '329239862452',
    projectId: 'authentication-75ad0',
    storageBucket: 'authentication-75ad0.appspot.com',
    iosClientId: '329239862452-b1ig66icm3iv1n5rjakst7gu51duibgt.apps.googleusercontent.com',
    iosBundleId: 'com.example.auth',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDnvHfhTtSrWABAYn2k8M0EhY6xIaVGQLE',
    appId: '1:329239862452:ios:3207a057ce876a6ea04be1',
    messagingSenderId: '329239862452',
    projectId: 'authentication-75ad0',
    storageBucket: 'authentication-75ad0.appspot.com',
    iosClientId: '329239862452-b1ig66icm3iv1n5rjakst7gu51duibgt.apps.googleusercontent.com',
    iosBundleId: 'com.example.auth',
  );
}
